@startuml
autonumber
'hide footbox
actor "Traffic Manager" as ADM

participant ":System" as Sys

ADM -> Sys : Know which places are closest to all other places
Sys --> ADM : Show the closest places


@enduml