@startuml
left to right direction

class Company{
    -name
}

class Port_warehouse {
    -name
    -latitude
    -longitude
    -continent
    -country
}


Company "1" -- "*" Port_warehouse : has
@enduml