@startuml
autonumber
'hide footbox
actor "Fleet Manager" as ADM

participant ":System" as Sys

ADM -> Sys : Receive an alert when the current energy generation units are not enough
Sys --> ADM : Send back an alert when the current energy generation units are not enough to provide energy to all refrigerated containers at once

@enduml