@startuml
left to right direction
skinparam packageStyle rectangle
actor ShipChiefEletricalEngineer
rectangle "System"{
    ShipChiefEletricalEngineer--(Want to receive an alert when the current energy generation units are not enough)
}
@enduml